FROM nginx
CMD ["nginx", "-g", "daemon off;"]


# FROM openresty/openresty:1.19.9.1-7-buster

# RUN mkdir -p /var/log/nginx \
#     && chown -R nobody:nogroup /var/log/nginx

# CMD ["/usr/local/openresty/bin/openresty", "-g", "daemon off;"]